/* Bilingual TH/EN — dictionary, context, helpers. */

const I18N = {
  en: {
    tagline_org: (org, ind) => `${org} · ${ind}`,
    settings: "Organization settings", toggle_theme: "Toggle theme", language: "Language",
    // steps
    step_org: "Organization", step_dept: "Departments", step_tool: "Tools", step_wf: "Workflows", step_gen: "Generate",
    // left panel
    library: "Library", tab_dept: "Depts", tab_tool: "Tools", tab_wf: "Flows",
    search_dept: "Search departments…", search_tool: "Search tools…", search_wf: "Search workflows…",
    grp_mgmt: "Management Core", grp_business: "Business", grp_support: "Support",
    add: "add", added: "added", on: "on", active: "Active",
    tools_n: (n) => `${n} ${n === 1 ? "tool" : "tools"}`,
    tool_hint: "Select a department on the canvas, then click tools here to attach them.",
    attaching_to: (d) => `Attaching to ${d}`, suggested: "suggested",
    features_n: (n) => `${n} features`, wf_hint: "Add cross-department workflows. Both departments are auto-added to your canvas.",
    // canvas
    canvas_title: "Office Canvas", w_depts: "departments", w_tools: "tools", w_workflows: "workflows",
    auto_arrange: "Auto-arrange",
    empty_title: "Drag a department to start building",
    empty_sub: "Click any department in the left library to drop it on the canvas. Then attach tools and wire up workflows.",
    no_tools_yet: "no tools yet", add_tool: "Add tool", select_add_tools: "Select & add tools from the library",
    workflows_label: "Workflows", wf_strip_empty: "No workflows yet — add cross-department flows from the Flows tab.",
    composing: (a) => `${a} is composing your system…`,
    // right panel
    ai_agent: "AI Agent", prompt_layers: "Prompt Layers", req: "REQ", opt: "OPT",
    t_prompt: "Prompt", t_json: "JSON", copy: "Copy", copied: "Copied",
    chars_n: (n) => `${n.toLocaleString()} chars`, tokens_n: (n) => `~${n} tokens`,
    prompt_empty: "Add a department to begin composing the prompt…",
    generate: "Generate Enterprise Blueprint", compiling: "Compiling 12 layers…", ready: "Blueprint ready",
    need_dept: "Add at least one department to generate.",
    layer_x12: (n) => `${n}/12`,
    // onboarding
    onb_title: "Create your organization",
    onb_p: "Set up your company, then drag departments and tools into the canvas. We compile your choices into a precise, copy-ready prompt for your coding agent.",
    f_org: "Organization name", ph_org: "e.g. Northwind Trading Co.",
    f_industry: "Industry", f_size: "Company size", f_template: "Start from a template",
    empty_canvas: "Empty canvas", depts_n: (n) => `${n} departments`, build_office: "Build My Office",
    // output
    out_title: "Enterprise Blueprint", out_sub: (org, a, n) => `${org} · generated by ${a} · ${n} sections`,
    dl_md: "Markdown", dl_json: "JSON", regenerate: "Regenerate",
    // pixel
    pixel_intro: "A 16-bit office room per department — copy the image prompt to generate the full scene in your image model.",
    pixel_character: "Character", pixel_screens: "Screens", pixel_tools: "Tools", pixel_walls: "Walls",
    copy_img_prompt: "Copy image prompt",
    // history
    history_title: "History", history_empty: "No saved workspaces yet. Click Generate to save your work.", history_clear: "Clear All", history_restore_confirm: "Are you sure you want to restore this workspace? Your current workspace configuration will be overwritten.",
  },
  th: {
    tagline_org: (org, ind) => `${org} · ${ind}`,
    settings: "ตั้งค่าองค์กร", toggle_theme: "สลับธีม", language: "ภาษา",
    step_org: "องค์กร", step_dept: "ส่วนงาน", step_tool: "เครื่องมือ", step_wf: "เวิร์กโฟลว์", step_gen: "สร้างระบบ",
    library: "คลังส่วนงาน", tab_dept: "ส่วนงาน", tab_tool: "เครื่องมือ", tab_wf: "เวิร์กโฟลว์",
    search_dept: "ค้นหาส่วนงาน…", search_tool: "ค้นหาเครื่องมือ…", search_wf: "ค้นหาเวิร์กโฟลว์…",
    grp_mgmt: "ส่วนบริหารหลัก", grp_business: "ส่วนธุรกิจ", grp_support: "ส่วนสนับสนุน",
    add: "เพิ่ม", added: "เพิ่มแล้ว", on: "เปิด", active: "ทำงานอยู่",
    tools_n: (n) => `${n} เครื่องมือ`,
    tool_hint: "เลือกส่วนงานบนพื้นที่ทำงานก่อน แล้วคลิกเครื่องมือที่นี่เพื่อแนบเข้าไป",
    attaching_to: (d) => `กำลังแนบให้ ${d}`, suggested: "แนะนำ",
    features_n: (n) => `${n} ฟีเจอร์`, wf_hint: "เพิ่มเวิร์กโฟลว์ข้ามส่วนงาน ระบบจะเพิ่มส่วนงานที่เกี่ยวข้องให้อัตโนมัติ",
    canvas_title: "พื้นที่ออฟฟิศ", w_depts: "ส่วนงาน", w_tools: "เครื่องมือ", w_workflows: "เวิร์กโฟลว์",
    auto_arrange: "จัดเรียงอัตโนมัติ",
    empty_title: "ลากส่วนงานมาวางเพื่อเริ่มต้น",
    empty_sub: "คลิกส่วนงานใดก็ได้จากคลังด้านซ้ายเพื่อวางลงบนพื้นที่ทำงาน จากนั้นแนบเครื่องมือและเชื่อมเวิร์กโฟลว์",
    no_tools_yet: "ยังไม่มีเครื่องมือ", add_tool: "เพิ่มเครื่องมือ", select_add_tools: "เลือกและเพิ่มเครื่องมือจากคลัง",
    workflows_label: "เวิร์กโฟลว์", wf_strip_empty: "ยังไม่มีเวิร์กโฟลว์ — เพิ่มได้จากแท็บเวิร์กโฟลว์",
    composing: (a) => `${a} กำลังประกอบระบบของคุณ…`,
    ai_agent: "เอเจนต์ AI", prompt_layers: "เลเยอร์พรอมป์ต", req: "จำเป็น", opt: "เสริม",
    t_prompt: "พรอมป์ต", t_json: "JSON", copy: "คัดลอก", copied: "คัดลอกแล้ว",
    chars_n: (n) => `${n.toLocaleString()} อักขระ`, tokens_n: (n) => `~${n} โทเคน`,
    prompt_empty: "เพิ่มส่วนงานเพื่อเริ่มประกอบพรอมป์ต…",
    generate: "สร้างพิมพ์เขียวระบบองค์กร", compiling: "กำลังประมวล 12 เลเยอร์…", ready: "พิมพ์เขียวพร้อมแล้ว",
    need_dept: "เพิ่มอย่างน้อยหนึ่งส่วนงานเพื่อสร้างระบบ",
    layer_x12: (n) => `${n}/12`,
    onb_title: "สร้างองค์กรของคุณ",
    onb_p: "ตั้งค่าบริษัทของคุณ แล้วลากส่วนงานและเครื่องมือลงบนพื้นที่ทำงาน ระบบจะประมวลตัวเลือกของคุณเป็นพรอมป์ตที่แม่นยำพร้อมคัดลอกไปใช้กับเอเจนต์เขียนโค้ดได้ทันที",
    f_org: "ชื่อองค์กร", ph_org: "เช่น บริษัท นอร์ทวินด์ เทรดดิ้ง",
    f_industry: "อุตสาหกรรม", f_size: "ขนาดบริษัท", f_template: "เริ่มจากเทมเพลต",
    empty_canvas: "พื้นที่ว่าง", depts_n: (n) => `${n} ส่วนงาน`, build_office: "สร้างออฟฟิศของฉัน",
    out_title: "พิมพ์เขียวระบบองค์กร", out_sub: (org, a, n) => `${org} · สร้างโดย ${a} · ${n} ส่วน`,
    dl_md: "Markdown", dl_json: "JSON", regenerate: "สร้างใหม่",
    pixel_intro: "ห้องออฟฟิศสไตล์ 16-bit ต่อหนึ่งส่วนงาน — คัดลอกพรอมป์ตสร้างภาพเพื่อนำไปสร้างฉากเต็มในโมเดลสร้างภาพของคุณ",
    pixel_character: "ตัวละคร", pixel_screens: "หน้าจอ", pixel_tools: "อุปกรณ์", pixel_walls: "ผนัง",
    copy_img_prompt: "คัดลอกพรอมป์ตสร้างภาพ",
    // history
    history_title: "ประวัติ", history_empty: "ยังไม่มีประวัติที่ถูกบันทึก คลิกสร้างระบบเพื่อบันทึกประวัติ", history_clear: "ล้างประวัติทั้งหมด", history_restore_confirm: "คุณแน่ใจหรือไม่ว่าต้องการกู้คืนประวัติชิ้นนี้? การตั้งค่าส่วนงานปัจจุบันบน Canvas จะถูกเขียนทับ",
  },
};

/* Department, workflow, layer, size, industry, template translations */
const TH = {
  depts: {
    dept_management: { name: "แผนกบริหาร", display: "แผนกบริหารและกลยุทธ์" },
    dept_hr: { name: "ทรัพยากรบุคคล", display: "ฝ่ายทรัพยากรบุคคล" },
    dept_finance: { name: "การเงินและบัญชี", display: "ฝ่ายการเงินและบัญชี" },
    dept_sales: { name: "ฝ่ายขาย", display: "ฝ่ายขาย" },
    dept_marketing: { name: "การตลาด", display: "ฝ่ายการตลาด" },
    dept_operations: { name: "ปฏิบัติการ", display: "ฝ่ายปฏิบัติการ" },
    dept_it: { name: "ไอที", display: "ฝ่ายเทคโนโลยีสารสนเทศ" },
    dept_rnd: { name: "วิจัยและพัฒนา", display: "ฝ่ายวิจัยและพัฒนา" },
    dept_purchasing: { name: "จัดซื้อ", display: "ฝ่ายจัดซื้อและจัดหา" },
    dept_cs: { name: "บริการลูกค้า", display: "ฝ่ายบริการลูกค้า" },
  },
  workflows: {
    wf_onboarding: "การรับพนักงานใหม่", wf_otc: "ออเดอร์สู่การรับเงิน", wf_procurement: "อนุมัติการจัดซื้อ",
    wf_budget: "คำขอจัดสรรงบประมาณ", wf_incident: "เหตุการณ์ด้านไอที", wf_complaint: "ข้อร้องเรียนลูกค้า",
    wf_launch: "เปิดตัวสินค้าใหม่", wf_reporting: "รายงานประจำเดือน",
  },
  layers: {
    Persona: "เพอร์โซนา", Mission: "ภารกิจ", Organization: "โครงสร้างองค์กร", "Business Context": "บริบทธุรกิจ",
    Features: "ฟีเจอร์", Workflows: "เวิร์กโฟลว์", "UX / UI": "UX / UI", Architecture: "สถาปัตยกรรม",
    "Tech Stack": "เทคโนโลยี", Execution: "การลงมือทำ", Governance: "การกำกับดูแล", "Output Format": "รูปแบบผลลัพธ์",
  },
  sizes: { S: "สตาร์ทอัพ", M: "เอสเอ็มอี", L: "ขนาดกลาง", XL: "องค์กรใหญ่" },
  industries: {
    "General Business": "ธุรกิจทั่วไป", "Retail & E-commerce": "ค้าปลีกและอีคอมเมิร์ซ", "Technology / SaaS": "เทคโนโลยี / SaaS",
    "Manufacturing": "การผลิต", "Healthcare": "สุขภาพ", "Financial Services": "บริการการเงิน",
    "Logistics": "โลจิสติกส์", "Education": "การศึกษา",
  },
  templates: { scratch: "เริ่มจากศูนย์", retail: "บริษัทค้าปลีก", tech: "สตาร์ทอัพเทคโนโลยี", mfg: "โรงงานผลิต" },
};

// English short-name -> id (for translating workflow step node labels)
const NAME_EN_TO_ID = {
  Management: "dept_management", HR: "dept_hr", Finance: "dept_finance", Sales: "dept_sales",
  Marketing: "dept_marketing", Operations: "dept_operations", IT: "dept_it", "R&D": "dept_rnd",
  Purchasing: "dept_purchasing", "Customer Service": "dept_cs",
};

const LangCtx = React.createContext("en");
function useLang() { return React.useContext(LangCtx); }
function useT() { const lang = React.useContext(LangCtx); return (k, ...a) => { const v = (I18N[lang] && I18N[lang][k]) ?? I18N.en[k] ?? k; return typeof v === "function" ? v(...a) : v; }; }

// name helpers
function dName(d, lang) { return lang === "th" && TH.depts[d.id] ? TH.depts[d.id].name : d.name; }
function dDisplay(d, lang) { return lang === "th" && TH.depts[d.id] ? TH.depts[d.id].display : d.display_name; }
function dSub(d, lang) { return lang === "th" ? d.name : d.display_name; } // TH: show English short as sub
function wfName(w, lang) { return lang === "th" && TH.workflows[w.id] ? TH.workflows[w.id] : w.name; }
function layerName(name, lang) { return lang === "th" && TH.layers[name] ? TH.layers[name] : name; }
function sizeLabel(id, label, lang) { return lang === "th" && TH.sizes[id] ? TH.sizes[id] : label; }
function industryLabel(v, lang) { return lang === "th" && TH.industries[v] ? TH.industries[v] : v; }
function tmplName(id, name, lang) { return lang === "th" && TH.templates[id] ? TH.templates[id] : name; }
function nodeTh(enName, lang) { if (lang !== "th") return enName; const id = NAME_EN_TO_ID[enName]; return id && TH.depts[id] ? TH.depts[id].name : enName; }

Object.assign(window, { I18N, TH, LangCtx, useLang, useT, dName, dDisplay, dSub, wfName, layerName, sizeLabel, industryLabel, tmplName, nodeTh });
