/* Output — S5 Blueprint Panel (+ Pixel Office tab) */
function BlueprintPanel({ blueprint, agentName, orgName, depts, onClose, onRegenerate }) {
  const lang = useLang(); const t = useT();
  const dataTabs = Object.keys(blueprint);
  const icons = { "Architecture": "layers", "DB Schema": "db", "API Design": "code", "Build Plan": "list", "Deployment": "rocket", "Security": "shield" };
  const PIXEL = "__pixel";
  const [tab, setTab] = React.useState(dataTabs[0]);
  const [copied, setCopied] = React.useState(false);

  const copy = () => {
    navigator.clipboard && navigator.clipboard.writeText(blueprint[tab]);
    setCopied(true); setTimeout(() => setCopied(false), 1400);
  };
  const download = (kind) => {
    let content, fname, type;
    if (kind === "md") {
      content = `# ${orgName} — Enterprise Blueprint\nGenerated by ${agentName}\n\n` + dataTabs.map((k) => `## ${k}\n\n\`\`\`\n${blueprint[k]}\n\`\`\``).join("\n\n");
      fname = "blueprint.md"; type = "text/markdown";
    } else {
      content = JSON.stringify(blueprint, null, 2); fname = "blueprint.json"; type = "application/json";
    }
    const url = URL.createObjectURL(new Blob([content], { type }));
    const a = document.createElement("a"); a.href = url; a.download = fname; a.click();
    setTimeout(() => URL.revokeObjectURL(url), 1000);
  };

  return (
    <div className="output-overlay">
      <div className="output-scrim" onClick={onClose} />
      <div className="output-panel">
        <div className="output-head">
          <div className="output-badge"><Icon name="check" size={18} /></div>
          <div style={{ flex: 1 }}>
            <div className="output-h">{t("out_title")}</div>
            <div className="output-sub">{t("out_sub", orgName, agentName, dataTabs.length)}</div>
          </div>
          <button className="icon-btn" onClick={onClose}><Icon name="x" size={18} /></button>
        </div>

        <div className="output-tabs">
          {dataTabs.map((k) => (
            <button key={k} className={"otab" + (tab === k ? " active" : "")} onClick={() => setTab(k)}>
              <Icon name={icons[k] || "code"} size={13} style={{ verticalAlign: "-2px", marginRight: 5 }} />{k}
            </button>
          ))}
          <button className={"otab otab-pixel" + (tab === PIXEL ? " active" : "")} onClick={() => setTab(PIXEL)}>
            <Icon name="grid" size={13} style={{ verticalAlign: "-2px", marginRight: 5 }} />{lang === "th" ? "ออฟฟิศ Pixel" : "Pixel Office"}
          </button>
        </div>

        <div className="output-body">
          {tab === PIXEL ? (
            <PixelRooms depts={depts} lang={lang} />
          ) : (
            <div className="code-block">
              <div className="code-head">
                <span className="code-name">{tab.toLowerCase().replace(/\s+/g, "_")}.txt</span>
                <button className={"insp-copy" + (copied ? " copied" : "")} onClick={copy}>
                  <Icon name={copied ? "check" : "copy"} size={13} /> {copied ? t("copied") : t("copy")}
                </button>
              </div>
              <pre>{blueprint[tab]}</pre>
            </div>
          )}
        </div>

        <div className="output-foot">
          <button className="btn-primary" onClick={() => download("md")}><Icon name="download" size={15} /> {t("dl_md")}</button>
          <button className="btn-ghost" onClick={() => download("json")}><Icon name="download" size={14} /> {t("dl_json")}</button>
          <div style={{ marginLeft: "auto" }}>
            <button className="btn-ghost" onClick={onRegenerate}><Icon name="sparkles" size={14} /> {t("regenerate")}</button>
          </div>
        </div>
      </div>
    </div>
  );
}

Object.assign(window, { BlueprintPanel });
